# Generated by Django 5.2.1 on 2025-05-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('worker', 'Ishchi'), ('programmer', 'Dasturchi'), ('doctor', 'Shifokor'), ('teacher', 'O‘qituvchi'), ('other', 'Boshqa')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('phone', models.CharField(max_length=20)),
                ('telegram', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('work_type', models.CharField(choices=[('remote', 'Uydan'), ('office', 'Ofisdan'), ('hybrid', 'Gibrid')], max_length=20)),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('telegram', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('worker', 'Ishchi'), ('programmer', 'Dasturchi'), ('doctor', 'Shifokor'), ('teacher', 'O‘qituvchi'), ('other', 'Boshqa')], max_length=20)),
                ('work_type', models.CharField(choices=[('remote', 'Uydan'), ('office', 'Ofisdan'), ('hybrid', 'Gibrid')], max_length=20)),
                ('experience', models.TextField(blank=True)),
                ('desired_position', models.CharField(max_length=100)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
