# Generated by Django 5.2.1 on 2025-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerad',
            name='category',
            field=models.CharField(choices=[('Kunlik ishchilar', 'Kunlik ishchilar'), ('Yukchilar', 'Yukchilar'), ('Santexniklar', 'Santexniklar'), ('Ustalar', 'Ustalar'), ('Apparatchilar', 'Apparatchilar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='category',
            field=models.CharField(choices=[('Kunlik ishchilar', 'Kunlik ishchilar'), ('Yukchilar', 'Yukchilar'), ('Santexniklar', 'Santexniklar'), ('Ustalar', 'Ustalar'), ('Apparatchilar', 'Apparatchilar')], max_length=20),
        ),
    ]
